"""#1094 — the DDL failure that killed 35 runs' databases has no #997 guard.

`_ddl_invariants_997` refuses to write DDL "containing a token postgres cannot parse", because
"postgres would reject the file and the database would never start". Its members are #988's
`?`, #969's bare `nullable`, #989's underscore defaults, #1031's constraint-marker column
names, and #1022's mismatched FK types.

Missing from that list is the one postgres names outright, across the run logs:

    multiple primary keys for table "videos" are not allowed      20
    multiple primary keys for table "follows" are not allowed     14
    multiple primary keys for table "likes_table" are not allowed  1

Same consequence, verbatim: `01_init.sql` is rejected, the database never starts, `docker_up`
fails. And it is the framework's own file — its first line reads "Auto-generated by
orchestrator._generate_database — do not hand-edit" — while r9's orchestrator filed two P0 bug
tasks against the BACKEND lane for it, which is #201's wall.

Today's renderer is correct: a contract that marks two columns `primary_key` produces ONE
composite clause, `PRIMARY KEY ("follower_id", "following_id")`, and rendering all 68 corpus
contracts yields 870 CREATE TABLE statements with **zero** duplicates. So this is a pure
regression guard: it cannot fire on anything the renderer emits today, and it makes the
failure that killed those runs unable to reach the file again.
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LLM = ROOT / "env_generator" / "llm_generator"
for _p in (ROOT, LLM):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from multi_agent.runtime.database_scaffold import (  # noqa: E402
    _ddl_invariants_997, _multi_pk_conflicts_1094, render_schema_sql)

_TWO_COLUMN_PKS = '''CREATE TABLE IF NOT EXISTS "videos" (
    "id" SERIAL PRIMARY KEY,
    "uuid" TEXT PRIMARY KEY,
    "title" TEXT
);
'''
_COMPOSITE = '''CREATE TABLE IF NOT EXISTS "follows" (
    "follower_id" INTEGER NOT NULL,
    "following_id" INTEGER NOT NULL,
    PRIMARY KEY ("follower_id", "following_id")
);
'''
_TWO_TABLES = _COMPOSITE + '''
CREATE TABLE IF NOT EXISTS "videos" (
    "id" SERIAL PRIMARY KEY,
    "title" TEXT
);
'''


class ThePostgresRejectionIsRefusedAtRenderTime(unittest.TestCase):

    def test_two_column_level_primary_keys_raise(self):
        with self.assertRaises(ValueError) as cm:
            _ddl_invariants_997(_TWO_COLUMN_PKS)
        msg = str(cm.exception)
        self.assertIn("videos", msg)
        self.assertIn("1094", msg)

    def test_the_conflict_names_the_table_and_the_count(self):
        out = _multi_pk_conflicts_1094(_TWO_COLUMN_PKS)
        self.assertEqual(out, [("videos", 2)])


class TheShapesThatAreFineStayFine(unittest.TestCase):

    def test_a_composite_clause_is_one_primary_key(self):
        self.assertEqual(_multi_pk_conflicts_1094(_COMPOSITE), [])
        _ddl_invariants_997(_COMPOSITE)          # must not raise

    def test_one_primary_key_per_table_across_many_tables(self):
        self.assertEqual(_multi_pk_conflicts_1094(_TWO_TABLES), [])
        _ddl_invariants_997(_TWO_TABLES)

    def test_empty_and_junk_are_safe(self):
        self.assertEqual(_multi_pk_conflicts_1094(""), [])
        self.assertEqual(_multi_pk_conflicts_1094("-- just a comment\n"), [])


class TodaysRendererIsAlreadyCorrect(unittest.TestCase):
    """The pin: a composite-PK contract yields ONE clause, so the guard is regression-only."""

    def test_a_two_column_pk_contract_renders_one_clause(self):
        sql = render_schema_sql({"follows": {"columns": [
            {"name": "follower_id", "type": "integer", "primary_key": True,
             "references": "users.id"},
            {"name": "following_id", "type": "integer", "primary_key": True,
             "references": "users.id"}]}})
        self.assertEqual(_multi_pk_conflicts_1094(sql), [])
        self.assertIn('PRIMARY KEY ("follower_id", "following_id")', sql)


if __name__ == "__main__":
    unittest.main()
