r"""#1202ad: one helper for "report a state, not a heartbeat", and three more sites using it.

The rule had been implemented five times, once per site, each with its own private dict and a
hand-written comparison — and I introduced one of the offenders myself two days after removing
the same noise elsewhere:

    #1202n   heal declines            r26 134 lines,  2 distinct states
    #1202p   declaration drift        r30 416 lines,  4 pages
    #1202v   seed audit "0 of N"      r30 213 lines,  1 state
    #1202ab  lane-page verdict        r32 280 lines,  9 pages
    #1202ac  unstaged assets (mine)   r32 117 lines,  1 set

A rule living in five copies drifts on the first edit to any of them, which is exactly what
`_imports_own_components` records about #905/#906. A sweep over r30/r31/r32 for warnings
repeating 25+ times found three more standing conditions restated per pass:

    281  BACKEND SKELETON generated by-construction from the contract
    273  DDL regenerated from the app's ORM models
    267  #739 ui_smoke_pass=True rests on N passing UI record(s) while M FAILED

All three now report through the helper.

★ It is NOT "log once". A state that MOVES is news and must be said again — including a move
BACK to a state already seen, which is how a flapping condition stays visible. Silence is only
for standing still.
"""

import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS_DIR.parent / "env_generator" / "llm_generator"))

from multi_agent.runtime.message_format import (  # noqa: E402
    reset_state_memo_1202ad, state_changed_1202ad)


def test_an_unchanged_state_is_reported_once():
    reset_state_memo_1202ad()
    assert state_changed_1202ad("s", (3, 17)) is True
    for _ in range(20):
        assert state_changed_1202ad("s", (3, 17)) is False


def test_a_moved_state_is_reported_again():
    reset_state_memo_1202ad()
    state_changed_1202ad("s", 1)
    assert state_changed_1202ad("s", 2) is True


def test_a_move_back_is_reported_too():
    """A flapping condition must stay visible; this is what separates it from log-once."""
    reset_state_memo_1202ad()
    state_changed_1202ad("s", "A")
    state_changed_1202ad("s", "B")
    assert state_changed_1202ad("s", "A") is True


def test_sites_do_not_silence_each_other():
    reset_state_memo_1202ad()
    assert state_changed_1202ad("page:Movies", 1) is True
    assert state_changed_1202ad("page:Shows", 1) is True


def test_a_state_that_cannot_be_represented_is_always_reported():
    class _Bad:
        def __repr__(self): raise RuntimeError("no repr")
    reset_state_memo_1202ad()
    assert state_changed_1202ad("s", _Bad()) is True
    assert state_changed_1202ad("s", _Bad()) is True


def test_the_memo_can_be_reset_by_prefix():
    reset_state_memo_1202ad()
    state_changed_1202ad("a:1", 1)
    state_changed_1202ad("b:1", 1)
    reset_state_memo_1202ad("a:")
    assert state_changed_1202ad("a:1", 1) is True     # forgotten
    assert state_changed_1202ad("b:1", 1) is False    # untouched


def test_the_three_sites_use_it():
    base = THIS_DIR.parent / "env_generator/llm_generator/multi_agent/runtime"
    for fname, site in (("scaffolder.py", "backend_skeleton"),
                        ("heal_pipeline.py", "orm_ddl_regen"),
                        ("delivery_gate.py", "ui_smoke_existential_739")):
        src = (base / fname).read_text(encoding="utf-8")
        assert "state_changed_1202ad" in src, fname
        assert site in src, fname
