"""#1093 — "remove or wire up the dead artifacts", for a file whose absence blocks the finish.

`agents_config.yaml` gates the frontend lane's finish on a set of `any_of` groups — the entry
point, App, the api service, and the mandatory auth/tenancy UI:

    - ["app/frontend/src/components/TenantPicker.jsx", ".../TenantPicker.tsx"]

r95, freshly generated by today's framework, routes `/login` to the lane's own
`LoginModalPage.jsx` and `/signup` to `SignupModalPage.jsx`, while
`components/TenantPicker.jsx`, `components/LoginPage.jsx`, `pages/LoginPage.jsx` and
`pages/SignupPage.jsx` sit with zero references. The coverage audit then reports them as dead
artifacts and the remediation says "remove or wire up" — but deleting the sole
`TenantPicker.jsx` makes the lane's next `finish` fail the required-files gate. The lane
cannot obey. #201's wall again: #1088 covered files the framework WRITES, these are files the
framework COMPELS the lane to write.

Measured over the corpus, of the 359 dead files left after #1088: **43 are the sole existing
member of an any_of group** (TenantPicker.jsx 40, pages/LoginPage.jsx 3) and 38 are members of
a group with another member present — where deleting one IS legal, so those keep reporting.
Sole-member is exactly the "cannot remove" case and is the whole exemption.

The signal is not lost, it is routed: #1090 registers the mandated TenantPicker and #1089
reports an unmounted component with advice the lane CAN act on — "render it from the page that
owns it, or drop the declaration" — instead of an instruction that contradicts another gate.
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path
from tempfile import mkdtemp

ROOT = Path(__file__).resolve().parents[1]
LLM_DIR = ROOT / "env_generator" / "llm_generator"
for _p in (str(ROOT), str(LLM_DIR)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from multi_agent.runtime.coverage_audit import (  # noqa: E402
    _finish_gate_any_of_groups_1093, scan_dead_files)

_APP = ("import Modal from './pages/LoginModalPage';\n"
        "export default function App(){ return <Modal/>; }\n")
_ORPHAN = "export default function X(){ return null; }\n"


def _tree(files) -> Path:
    root = Path(mkdtemp())
    for rel in files:
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(_APP if rel.endswith("App.jsx") else _ORPHAN, encoding="utf-8")
    return root


def _dead(files) -> set:
    return {d["path"] for d in scan_dead_files(_tree(files))}


class TheSoleMandatedMemberIsNotDeletable(unittest.TestCase):

    def test_r95s_tenant_picker(self):
        dead = _dead(["frontend/src/App.jsx",
                      "frontend/src/pages/LoginModalPage.jsx",
                      "frontend/src/components/TenantPicker.jsx"])
        self.assertNotIn("frontend/src/components/TenantPicker.jsx", dead,
                         "the lane is told to delete a file its own finish gate requires")


class ADeletableDuplicateStillReports(unittest.TestCase):
    """When another member of the group exists, removing one IS legal — keep reporting."""

    def test_both_login_pages_still_read_dead(self):
        dead = _dead(["frontend/src/App.jsx",
                      "frontend/src/pages/LoginModalPage.jsx",
                      "frontend/src/pages/LoginPage.jsx",
                      "frontend/src/components/LoginPage.jsx"])
        self.assertIn("frontend/src/pages/LoginPage.jsx", dead)
        self.assertIn("frontend/src/components/LoginPage.jsx", dead)


class EverythingElseIsUnchanged(unittest.TestCase):

    def test_an_unmandated_orphan_is_still_dead(self):
        dead = _dead(["frontend/src/App.jsx",
                      "frontend/src/pages/LoginModalPage.jsx",
                      "frontend/src/components/Orphan.jsx"])
        self.assertIn("frontend/src/components/Orphan.jsx", dead)

    def test_a_mandated_file_that_IS_used_was_never_dead(self):
        dead = _dead(["frontend/src/App.jsx", "frontend/src/pages/LoginModalPage.jsx"])
        self.assertNotIn("frontend/src/App.jsx", dead)


class TheGroupsComeFromTheConfig(unittest.TestCase):
    """Sourced from agents_config.yaml, not retyped — the #1090 drift-guard pattern."""

    def test_the_auth_ui_group_is_present(self):
        groups = _finish_gate_any_of_groups_1093()
        flat = {m for g in groups for m in g}
        self.assertIn("frontend/src/components/TenantPicker.jsx", flat)
        self.assertIn("frontend/src/components/LoginPage.jsx", flat)

    def test_the_alternatives_stay_grouped(self):
        groups = _finish_gate_any_of_groups_1093()
        picker = [g for g in groups if "frontend/src/components/TenantPicker.jsx" in g]
        self.assertTrue(picker, "the TenantPicker group vanished from the config")
        self.assertGreaterEqual(len(picker[0]), 2, "a group with one member cannot be any_of")


if __name__ == "__main__":
    unittest.main()
